// <auto-generated />
using System;
using IKProjesi.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IKProjesi.API.Migrations
{
    [DbContext(typeof(IKDbContext))]
    [Migration("20250718095117_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalisanSifre", b =>
                {
                    b.Property<int>("CalisanSifreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalisanSifreID"));

                    b.Property<int>("CalisanID")
                        .HasColumnType("int");

                    b.Property<int?>("CalisanID1")
                        .HasColumnType("int");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CalisanSifreID");

                    b.HasIndex("CalisanID")
                        .IsUnique();

                    b.HasIndex("CalisanID1");

                    b.ToTable("CalisanSifreler");
                });

            modelBuilder.Entity("IKProjesi.API.Models.Calisan", b =>
                {
                    b.Property<int>("CalisanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalisanID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("DepartmanID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IseGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Maas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PozisyonID")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CalisanID");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("IKProjesi.API.Models.Departman", b =>
                {
                    b.Property<int>("DepartmanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmanID"));

                    b.Property<string>("DepartmanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmanID");

                    b.ToTable("Departmanlar");
                });

            modelBuilder.Entity("IKProjesi.API.Models.Pozisyon", b =>
                {
                    b.Property<int>("PozisyonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PozisyonID"));

                    b.Property<string>("PozisyonAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PozisyonID");

                    b.ToTable("Pozisyonlar");
                });

            modelBuilder.Entity("CalisanSifre", b =>
                {
                    b.HasOne("IKProjesi.API.Models.Calisan", null)
                        .WithOne("Sifre")
                        .HasForeignKey("CalisanSifre", "CalisanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IKProjesi.API.Models.Calisan", "Calisan")
                        .WithMany()
                        .HasForeignKey("CalisanID1");

                    b.Navigation("Calisan");
                });

            modelBuilder.Entity("IKProjesi.API.Models.Calisan", b =>
                {
                    b.Navigation("Sifre")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
